on:
  pull_request:

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v3 # docs https://pnpm.io/continuous-integration#github-actions
        with:
          version: 9
      # Further steps for your build/test process
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm test
